# -*- coding: utf-8 -*-
"""09.QuickSortSwap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R6Uf8W_Hu3_jcXySyB8SyqEsqNounFUL
"""

def swap(X, i, j):
  temp = X[i]
  X[i] = X[j]
  X[j] = temp

def partition(X, left, right):
  point = X[right]
  index = left
  for i in range(left, right):
    if X[i] <= point:
      swap(a, i, index)
      index = index + 1
  swap(a, right, index)
  return index

def quicksort(X, left, right):
  if left >= right:
    return
  point = partition(a, left, right)
  quicksort(X, left, point - 1)
  quicksort(X, point + 1, right)
 

if __name__ == '__main__':
  a = [2,7,6,1,3,5,4,9,8,10]
  print(a)
  quicksort(a, 0, len(a) - 1)
  print(a)

